export DOTFILES_HOME=~/dotfiles

# Silence Catalina
export BASH_SILENCE_DEPRECATION_WARNING=1

# Other flags
export ARCHFLAGS="-arch x86_64"
export ERL_AFLAGS="-kernel shell_history enabled"

# Main path configuration
export PATH="$HOME/bin:/usr/local/bin:$PATH"

source $DOTFILES_HOME/shell/env
source $DOTFILES_HOME/shell/prompt
source $DOTFILES_HOME/shell/alias

source $DOTFILES_HOME/shell/extras/android
source $DOTFILES_HOME/shell/extras/docker
source $DOTFILES_HOME/shell/extras/ds_store
source $DOTFILES_HOME/shell/extras/filesystem
source $DOTFILES_HOME/shell/extras/git
source $DOTFILES_HOME/shell/extras/hidden_files
source $DOTFILES_HOME/shell/extras/history_of_file
source $DOTFILES_HOME/shell/extras/homebrew
source $DOTFILES_HOME/shell/extras/nix
source $DOTFILES_HOME/shell/extras/nvm
source $DOTFILES_HOME/shell/extras/go
source $DOTFILES_HOME/shell/extras/process
source $DOTFILES_HOME/shell/extras/psql
source $DOTFILES_HOME/shell/extras/py
source $DOTFILES_HOME/shell/extras/rbenv
source $DOTFILES_HOME/shell/extras/svn
source $DOTFILES_HOME/shell/extras/title

[[ -r ~/.bashrc ]] && . ~/.bashrc
[[ -r ~/.bash_aliases ]] && . ~/.bash_aliases
[[ -r ~/.bash_hacks ]] && . ~/.bash_hacks
[[ -r ~/.bash_servers ]] && . ~/.bash_servers
