export DOTFILES_HOME=~/dotfiles

source $DOTFILES_HOME/shell/env
source $DOTFILES_HOME/shell/prompt
source $DOTFILES_HOME/shell/alias

source $DOTFILES_HOME/shell/extras/ds_store
source $DOTFILES_HOME/shell/extras/filesystem
source $DOTFILES_HOME/shell/extras/hidden_files
source $DOTFILES_HOME/shell/extras/history_of_file
source $DOTFILES_HOME/shell/extras/nvm
source $DOTFILES_HOME/shell/extras/go
source $DOTFILES_HOME/shell/extras/process
source $DOTFILES_HOME/shell/extras/psql
source $DOTFILES_HOME/shell/extras/rvm
source $DOTFILES_HOME/shell/extras/svn

[[ -r ~/.bashrc ]] && . ~/.bashrc
[[ -r ~/.bash_aliases ]] && . ~/.bash_aliases
[[ -r ~/.bash_hacks ]] && . ~/.bash_hacks
[[ -r ~/.bash_servers ]] && . ~/.bash_servers
