"-------------------------------"
" Set up packages with Pathogen "
"-------------------------------"

source ~/dotfiles/vim/bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect('bundle/{}', '~/dotfiles/vim/bundle/{}')
filetype plugin indent on

"----------"
" Settings "
"----------"

set encoding=utf-8
scriptencoding utf-8

set backspace=eol,start,indent
set whichwrap+=<,>,h,l

set background=dark
set display+=lastline
set guitablabel=%t
set history=100
set hlsearch
set laststatus=2
set magic
set number
set nowrap
set ruler
set showmatch
set showmode
set textwidth=0
set wildmenu

set backupdir=~/.vim/tmp/backup//
set directory=~/.vim/tmp/swap//
set undodir=~/.vim/tmp/undo//

"--------------"
" Code folding "
"--------------"

set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=1

"---------------------"
" Syntax Highlighting "
"---------------------"

syntax enable

set expandtab
set shiftwidth=2
set smarttab
set tabstop=2

set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines

"----------"
" Mappings "
"----------"

let mapleader="\<Space>"

" Edit vimrc file
nmap <Leader>vr :sp $MYVIMRC<CR>
nmap <Leader>so :source $MYVIMRC<CR>

" Duplicate line
nmap <Leader>d yyz

" Tab/pane shortcuts
nmap <Leader>tn :tabnew<CR>
nmap <Leader>tc :tabc<CR>
nmap <Leader>pv :vsplit<CR>
nmap <Leader>ph :split<CR>
nmap <Leader>pc :close<CR>

" Moving in tabs
nmap <C-L> :tabn<CR>
nmap <C-H> :tabp<CR>

" Exit modes more easily
imap jk <Esc>
imap kj <Esc>

" Quick jump to start/end of lines
nmap <Leader>l $
nmap <Leader>h ^

" clearing highlighted search
nmap <silent> <Leader>/ :nohlsearch<CR>

" Make splits a bit more manageable.
nnoremap <Leader>1 :vs<CR><C-w>l
nnoremap <Leader>2 :split<CR><C-w>j
nnoremap <C-Up> :bn<CR>
nnoremap <C-Down> :bp<CR>

map <C-e> :NERDTreeToggle<CR>
nmap <Leader>sw :StripWhitespace<CR>

cnoreabbrev w. w %:h/

"---------"
" Plugins "
"---------"

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_switch_buffer=0
let g:ctrlp_working_path=0
let g:ctrlp_use_caching=0

let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden
      \ --ignore .git
      \ --ignore .svn
      \ --ignore .hg
      \ --ignore .DS_Store
      \ --ignore "**/*.pyc"
      \ -g ""'

set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.map

let g:netrw_liststyle=3

let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#fnamemod=':t'
let g:airline#extensions#tabline#show_buffers=0
let g:airline#extensions#tabline#fnamecollapse=0
let g:airline#extensions#tabline#show_tab_nr=1
let g:airline#extensions#tabline#tab_nr_type=1 " tab number

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_ignore_files=['\.html$', '\c\.h$', '\.css$', '\.hbs']
