"-------------------------------"
" Set up packages with Pathogen "
"-------------------------------"

source ~/dotfiles/vim/bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect('bundle/{}', '~/dotfiles/vim/bundle/{}')
filetype plugin indent on

"----------"
" Settings "
"----------"

set encoding=utf-8
scriptencoding utf-8

set backspace=eol,start,indent
set whichwrap+=<,>,h,l

set background=dark
set display+=lastline
set guitablabel=%t
set history=100
set hlsearch
set laststatus=2
set magic
set number
set nowrap
set ruler
set showmatch
set showmode
set textwidth=0
set wildmenu

set backupdir=~/.vim/tmp/backup//
set directory=~/.vim/tmp/swap//
set undodir=~/.vim/tmp/undo//

"---------------------"
" Syntax Highlighting "
"---------------------"

syntax enable

set expandtab
set shiftwidth=2
set smarttab
set tabstop=2

set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines

"----------"
" Mappings "
"----------"

let mapleader=","

" Edit vimrc file
nmap <Leader>vr :sp $MYVIMRC<CR>
nmap <Leader>so :source $MYVIMRC<CR>

" Duplicate line
nmap <Leader>d yyz

" Tab/pane shortcuts
nmap <Leader>tn :tabnew<CR>
nmap <Leader>tc :tabc<CR>
nmap <Leader>pv :vsplit<CR>
nmap <Leader>ph :split<CR>
nmap <Leader>pc :close<CR>

" Moving in tabs
nmap <C-L> :tabn<CR>
nmap <C-H> :tabp<CR>

" Exit modes more easily
imap jk <Esc>
imap kj <Esc>

" Moving lines
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" clearing highlighted search
nmap <silent> <Leader>/ :nohlsearch<CR>

" Make splits a bit more manageable.
nnoremap <Leader>1 :vs<CR><C-w>l
nnoremap <Leader>2 :split<CR><C-w>j
nnoremap <C-Up> :bn<CR>
nnoremap <C-Down> :bp<CR>

map <C-e> :NERDTreeToggle<CR>

cnoreabbrev w. w %:h/

"---------"
" Plugins "
"---------"

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_switch_buffer=0
let g:ctrlp_working_path=0
let g:ctrlp_use_caching=0

let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden
      \ --ignore .git
      \ --ignore .svn
      \ --ignore .hg
      \ --ignore .DS_Store
      \ --ignore "**/*.pyc"
      \ -g ""'

set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.map

let g:netrw_liststyle=3

let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#fnamemod=':t'
let g:airline#extensions#tabline#show_buffers=0
let g:airline#extensions#tabline#fnamecollapse=0
let g:airline#extensions#tabline#show_tab_nr=1
let g:airline#extensions#tabline#tab_nr_type=1 " tab number
