# zprofile - set the environment for login shells
# .zshenv → .zprofile → .zshrc → .zlogin → .zlogout

export DOTFILES_HOME=~/dotfiles

export PATH="$HOME/.local/bin:$PATH"

source $DOTFILES_HOME/shell/env
source $DOTFILES_HOME/shell/alias

source $DOTFILES_HOME/shell/zsh/prompt
source $DOTFILES_HOME/shell/zsh/options

source $DOTFILES_HOME/shell/extras/git
source $DOTFILES_HOME/shell/extras/hidden_files
source $DOTFILES_HOME/shell/extras/homebrew
