# zshrc - set the environment for interactive shells
# .zshenv → .zprofile → .zshrc → .zlogin → .zlogout

export DOTFILES_HOME=~/dotfiles


source $DOTFILES_HOME/shell/zsh/nvm
source $DOTFILES_HOME/shell/zsh/pyenv
source $DOTFILES_HOME/shell/zsh/rbenv

source $DOTFILES_HOME/shell/extras/herd
source $DOTFILES_HOME/shell/extras/mysql
